version: '3.8'
services:

  postgres:
    image: postgres:alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
        POSTGRES_PASSWORD: showtime
        POSTGRES_USER: showtime
        POSTGRES_DB: showtime

  brave:
    # Built from https://github.com/ystv/brave
    image: registry.comp.ystv.co.uk/brave:latest
    ports:
      - "5000:5000"

  nginx:
    image: registry.comp.ystv.co.uk/nginx/nginx-rtmp:latest
    ports:
      - '1935:1935'
      - '8081:80'
    depends_on:
      - showtime # otherwise you'll get "[emerg] host not found in url "showtime:8080/api/hooks/nginx/on_publish""
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/wait-for-it.sh:/wait-for-it.sh
    command: ["/wait-for-it.sh", "showtime:8080", "--", "nginx", "-g", "daemon off;"]

  showtime:
    build: .
    depends_on:
      - postgres
      - brave
    ports:
      - '8080:8080'
    volumes:
      - ./credentials:/run/credentials
      - ./docker/wait-for-it.sh:/wait-for-it.sh
    command: ["/wait-for-it.sh", "postgres:5432", "--", "/usr/bin/showtime"]
    environment:
      - ST_DEBUG=true
      - ST_INGEST_ADDR=rtmp://nginx:1935/ingest
      - ST_OUTPUT_ADDR=rtmp://nginx:1935/output
      - ST_BASE_SERVE_ADDR=http://showtime:8080
      - ST_BRAVE_ADDR=http://brave:5000
      - ST_DB_HOST=postgres
      - ST_DB_PORT=5432
      - ST_DB_SSLMODE=disable
      - ST_DB_USERNAME=showtime
      - ST_DB_PASSWORD=showtime
      - ST_DB_DBNAME=showtime
      - ST_DB_AUTO_INIT=true
      - ST_CRED_PATH=/run/credentials

volumes:
  pgdata: { }